services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=microservices_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  app1:
    build:
      context: ./app1
      ssh:
        - default
    ports:
      - "8001:8000"
    container_name: app1_service
    environment:
      - DB_NAME=microservices_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    command: >
      sh -c "python manage.py migrate &&
             gunicorn app1.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db

  app2:
    build:
      context: ./app2
      ssh:
        - default
    ports:
      - "8002:8000"
    container_name: app2_service
    environment:
      - DB_NAME=microservices_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    command: >
      sh -c "python manage.py migrate &&
             gunicorn app2.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db

volumes:
  postgres_data: